services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nc:
    image: nextcloud:apache
    env_file:
      - .env
    ports:
      - 80:80
    restart: always
    volumes:
      - nc_data:/var/www/html
    depends_on:
      - db
volumes:
  db_data:
  nc_data:
